# Hydra configuration file for training

train:
  imgs: 'data/train_imgs/'    #
  mpms: 'data/train_mpms/'    #
  itvs: [1, 3, 5, 7, 9]                   # Multiple patterns are OK like [1, 3, 5, 7, 9]
  epochs: 300                  # Number of epoch
  batch_size: 16               # Batch size
  lr: 0.0001                  # Learning rate of Adam
  
pre: True
norm: True
kernel_size: 7
sigma: 0.25
threshold: 0.5 
crit: 'mse' 
consistency_weights: 0.5

world_size: 4

eval:
  imgs:      # None is OK. In that case, eval.rate in the training data is used for evaluation.
  mpms:      # None is OK
  itvs: [9]                   # Multiple patterns are OK like [1, 3, 5, 7, 9]
  rate: 0.2                   # Evaluation rate for no eval data

output:
  save: True
  dir: 'checkpoints/'

load: False                   # If you use a trained model, please rewrite it.

dataloader:
  edge: 10                    # Image edge range (This area will not be cropped)
  height: 256                 # Number of pixel of crop height
  width: 256                  # Number of pixel of crop width

info:
  direction: parallel         # Direction type of MPM
